### PR TITLE
141 incore lab quota read from endpoint

### PR DESCRIPTION
**Pull request by longshuicy**
Not ready to be reviewed until the service PR in place https://github.com/IN-CORE/incore-services/pull/218

### CODE REVIEW

**Comment by ylyangtw** [comment]
seems like the service has been merged, maybe this is ready for review?

**Review by navarroc — APPROVED** [review]

**Review by Rashmil-1999 — APPROVED** [review]
I think your formatter has changed :P many formatting diffs. Everything works fine... approving

**Comment by navarroc** [comment]
I compared my incore lab usage on incore-dev and using this running locally and it looks good. I'm not sure if there is anything else I can test. Let me know.

**Comment by longshuicy** [comment]
> I think your formatter has changed :P many formatting diffs. Everything works fine... approving

Yes at some point we need to figure out how can we set the same linting. Is there already an issue?

**Pull request merged**
