### PR TITLE
call the endpoint itself on tab selection

### PR DESCRIPTION
**Pull request by longshuicy**
whenever select a viewer, it calls the document itself; then INCORE-auth would be able to pick it up and record as 1 time visit of the page
image

### CODE REVIEW

**Comment by robkooper** [comment]
@longshuicy can you do something similar for when a user goes to jupyterhub?

**Comment by longshuicy** [comment]
> @longshuicy can you do something similar for when a user goes to jupyterhub?

Any specific endpoint do you want jupyterhub to call? or just `/jupyterhub` would be good

**Comment by robkooper** [comment]
jupyterhub sounds good

**Review by robkooper — APPROVED** [review]
missing changelog, otherwise good to merge.

**Comment by longshuicy** [comment]
> missing changelog, otherwise good to merge.

Looks like we'll actually have more issues in this release (and actually have a release). I will update the changelog in the release PR till the end.

**Review by vnarah2 — APPROVED** [review]

**Pull request merged**
