### PR TITLE
160 add links to slack channel and mailing list

### PR DESCRIPTION
**Pull request by longshuicy**
image

image

### CODE REVIEW

**Comment by navarroc** [comment]
I would maybe change inquiries to questions. Otherwise I think it looks good.

**Review by ylyangtw — APPROVED** [review]
UI looks nice. Changes look no problem

**Comment by longshuicy** [comment]
> I would maybe change inquiries to questions. Otherwise I think it looks good.

done

**Comment by navarroc** [comment]
Oh, one other thing, testbed channels are all locked. We might need to remove that text.

**Comment by longshuicy** [comment]
> Oh, one other thing, testbed channels are all locked. We might need to remove that text.

updated

**Comment by navarroc** [comment]
The slack logo doesn't render for me on my machine. Do you see it @ylyangtw ? Also, I'm not sure what's better, to link to the shortened URL or the long URL. In the docs, I used the long url. I'm not sure how users will feel about clicking on a shortened URL. Thoughts from others?

**Review by navarroc — APPROVED** [review]

**Pull request merged**
