### PR TITLE
Use the allocation from service endpoint #69

### PR DESCRIPTION
**Pull request by longshuicy**
To test run `npm run start:dev`

Allocations now coming from service endpoints instead of hard-coded json (except jupyter lab setting)
image

image

### CODE REVIEW

**Review by ywkim312 — APPROVED** [review]
I don't know the code. I am approving since it worked for me.

**Comment by navarroc** [comment]
Signed in as my user, does this look right? I'm suprised my quote differs from @longshuicy. 
incore-quota

**Comment by longshuicy** [comment]
> Signed in as my user, does this look right? I'm suprised my quote differs from @longshuicy. incore-quota

Hmm looking at the crazy amount of file size you are allowed....
Let's hold on merging this.

**Comment by navarroc** [comment]
> wow your allocation is huge. Are you using dev?

Yes, and it looks right based on what the spaces/api/allocations endpoint returns, but I have no idea why mine is set so high. Was someone testing something?

**Review by navarroc — APPROVED** [review]

**Comment by ywkim312** [comment]
> > wow your allocation is huge. Are you using dev?
> 
> Yes, and it looks right based on what the spaces/api/allocations endpoint returns, but I have no idea why mine is set so high. Was someone testing something?

@longshuicy In your user final quota calculation, is there a calculation for incore_admin?

**Pull request merged**
