### PR TITLE
86 webpack upgrade from v4 to v5

### PR DESCRIPTION
**Pull request by longshuicy**
Upgrade webpack from version 4 to 5 and fix a few vulnerabilities here.
There are still some left 
```
# npm audit report

postcss  <7.0.36
Severity: moderate
Regular Expression Denial of Service in postcss - https://github.com/advisories/GHSA-566m-qj78-rww5
fix available via `npm audit fix --force`
Will install autoprefixer@10.4.8, which is a breaking change
node_modules/autoprefixer/node_modules/postcss
  autoprefixer  1.0.20131222 - 8.6.5
  Depends on vulnerable versions of postcss
  node_modules/autoprefixer

scss-tokenizer  *
Severity: high
Regular expression denial of service in scss-tokenizer - https://github.com/advisories/GHSA-7mwh-4pqv-wmr8
fix available via `npm audit fix --force`
Will install node-sass@4.5.3, which is a breaking change
node_modules/scss-tokenizer
  sass-graph  >=2.2.0
  Depends on vulnerable versions of scss-tokenizer
  node_modules/sass-graph
    node-sass  >=4.6.0
    Depends on vulnerable versions of sass-graph
    node_modules/node-sass

underscore  1.3.2 - 1.12.0
Severity: high
Arbitrary Code Execution in underscore - https://github.com/advisories/GHSA-cf4h-3jhx-xvhq
fix available via `npm audit fix --force`
Will install isparta-loader@1.0.0, which is a breaking change
node_modules/underscore
  nomnomnomnom  *
  Depends on vulnerable versions of underscore
  node_modules/nomnomnomnom
    isparta  >=3.1.0
    Depends on vulnerable versions of nomnomnomnom
    node_modules/isparta
      isparta-loader  >=2.0.0
      Depends on vulnerable versions of isparta
      node_modules/isparta-loader

9 vulnerabilities (2 moderate, 7 high)
```

### CODE REVIEW

**Comment by navarroc** [comment]
I tested basic functionality for each of the different viewers - previewing data, searching for data, etc and I didn't see any issues. The only thing of note was I see some console errors about the material-ui theme, but it didn't seem to have any adverse effects. 

If possible, it might be worthwhile for @ywkim312 to put this branch incore-dev so we can test it there as well. Not a requirement, but could be worth doing to verify we can build a docker and deploy it without issue. I'm going to approve this since I don't see any issues, but I'm happy to test this further if we deploy it on dev.

**Review by navarroc — APPROVED** [review]

**Comment by navarroc** [comment]
Do you want to add a changelog entry now or later?

**Comment by navarroc** [comment]
Can you also create the next milestone (I assume 1.3.0) and add issue #86 to it?

**Comment by ywkim312** [comment]
I have deployed the PR to dev cluster so please test it out.

**Review by nunezco2 — APPROVED** [review]

**Pull request merged**
